Repository team-serius/doldol-server, pull requests merged in 2025-06, with the labels that each got.

#81 [REFACTOR] 인증/인가 API 리팩토링
  src/main/java/doldol_server/doldol/auth/controller/AuthController.java
  src/main/java/doldol_server/doldol/auth/filter/CustomLogoutFilter.java
  src/main/java/doldol_server/doldol/auth/util/ResponseUtil.java
Labels: refactor

#94 [FIX] 쿠키 도메인 설정
  src/main/java/doldol_server/doldol/auth/util/CookieUtil.java
  src/main/resources/application.yml
Labels: fix

#111 [REFACTOR] 신고 컨트롤러 분리, 스웨거 반영
  src/main/java/doldol_server/doldol/common/config/SecurityConfig.java
  src/main/java/doldol_server/doldol/report/controller/AdminReportController.java
  src/main/java/doldol_server/doldol/report/controller/UserReportController.java
Labels: refactor

#119 [REFACTOR] 초대 코드 추가
  src/main/java/doldol_server/doldol/rollingPaper/dto/response/CreatePaperResponse.java
  src/main/java/doldol_server/doldol/rollingPaper/dto/response/PaperDetailResponse.java
  src/main/java/doldol_server/doldol/rollingPaper/service/PaperService.java
Labels: refactor

#123 [FIX] 관리자만 해당 회원탈퇴 가능
  src/main/java/doldol_server/doldol/common/config/SecurityConfig.java
Labels: bug, fix

#135 [REFACTOR] 잘가...나의 이메일 디자인들아
  src/main/java/doldol_server/doldol/auth/service/EmailService.java
  src/main/resources/static/images/logo.png
  src/main/resources/templates/tempPassword.html
  src/main/resources/templates/verificationCode.html
Labels: refactor

#167 [FIX] 메세지 공개 날짜 수정
  src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
Labels: bug, fix

#173 [BUG] 받은 메시지 삭제 이슈 해결
  src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustom.java
  src/main/java/doldol_server/doldol/rollingPaper/repository/custom/MessageRepositoryCustomImpl.java
  src/main/java/doldol_server/doldol/rollingPaper/service/MessageService.java
Labels: bug, fix
